#+SETUPFILE: /home/krutna/.emacs.d/org-mode/orgs/setup/setup.org
#+LANGUAGE: ru
#+AUTHOR: Krutko Nikita / KrutNA

* Программирование

** 1 Семестр

Препод: Богатов О.Г., просто душка. 

C++; основы программирования, с нуля.

(От себя могу предлжить почитать https://ravesli.com/uroki-cpp)

Лабораторные: презентации, объяснение материала, тесты.

Практика: программирование на парах. Можно на своём устройстве.

** 2 Семестр

C#; курсовая работа, проект. Начало ООП (Хз как, учитывая, что это от и до ООП язык).

Пример курсовой: https://github.com/CatDany/NewPogodi

* Физическая культура и спорт (лекции)

Конспектирование лекций, презентаций. ЗОЖ, упражнения и т.д.

Возможны частные проверки конспектов.

Возможна позже практика.
Секции: 
- ОФП
- Спец группа
- Плавание
- Тяжёлая атлетика
- Лёгкая атлетика
- Футбол, Волейбол
- Баскетбол
- Аэробика
- Борьба

* Информатика (aka Дискретная математика, см wiki)

Булева алгебра. Бинаркное представление. Форматы чисел. 

* Инженерия и компьютерная графика

Черчение в Компас 3D, пара программ на C# (?). Всё по методичке.

* Математика

Про преподов ничего не известно. Есть темы за весь курс.

* Открытое ПО (ОПО)

Linux <3. Установка, терминал. (Астра или любой другой)

(Рекомендую: Mind / Debian / Manjaro / 

* Основы проф деятельности (ОПД)

Word / Excell / etc.

* Физика

Не особо ебут, средне. Но как повезёт с преподами.
